name: Simple Workflow
on:
  push: 
    branches: 
      - master
jobs:
  testjobwork:
    runs-on: ubuntu-latest ## runner
    steps: 
    - name: USE AN ACTION (CHECKOUT ACTION)
      uses: actions/checkout@v6

    - name: BUILD THE DOCKER IMAGE 
      run: sudo docker build -t testbuild:latest ./.devops

    - name: LOGIN TO USER'S DOCKER HUB
      run: sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: TAG THE DOCKER IMAGE
      run: sudo docker tag testbuild:latest ${{ secrets.DOCKERHUB_USERNAME }}/testbuild:latest

    - name: PUSH TO DOCKER HUB
      run: sudo docker push ${{ secrets.DOCKERHUB_USERNAME }}/testbuild:latest