name: Simple Workflow
on:
  push: 
    branches: 
      - master
jobs:
  testjobwork:
    runs-on: ubuntu-latest ## runner
    steps: 
    - name: USE AN ACTION (CHECKOUT ACTION)
      uses: actions/checkout@v6

    - name: BUILD THE DOCKER IMAGE 
      run: sudo docker build -t testbuild:latest .

    - name: LOGIN TO DOCKER HUB
      run: sudo docker login -u theoafactor -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: PUSH TO DOCKER HUB
      run: sudo docker push testbuild:latest